import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const owner='00000000-0000-4000-8000-000000000001',user='00000000-0000-4000-8000-000000000002',other='00000000-0000-4000-8000-000000000003';
async function fixture(){const pg=new PGlite();await pg.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');`);const sql=(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8')).replace('create extension if not exists pgcrypto;','');await pg.exec(sql);await pg.query(`insert into auth.users(id,email,email_confirmed_at)values($1,'trooperhaps@gmail.com',now()),($2,'builder@example.com',now()),($3,'other@example.com',now())`,[owner,user,other]);for(const id of [owner,user,other])await pg.query('select ensure_account($1)',[id]);return pg;}
async function a(pg:PGlite,id=user){return (await pg.query<any>('select * from accounts where id=$1',[id])).rows[0]}
async function create(pg:PGlite,id=user){return (await pg.query<any>(`select create_project($1,'Test app','','{"index.html":"hello"}') as p`,[id])).rows[0].p}
test('verified owner is bound to UUID, not editable metadata',async()=>{const pg=await fixture();try{assert.equal((await a(pg,owner)).role,'owner');await pg.query(`update auth.users set raw_user_meta_data='{"role":"owner","email":"trooperhaps@gmail.com"}'where id=$1`,[user]);await pg.query('select ensure_account($1)',[user]);assert.equal((await a(pg,user)).role,'member');await pg.query('update auth.users set email_confirmed_at=null where id=$1',[other]);await assert.rejects(()=>pg.query('select ensure_account($1)',[other]),/Not authorised/);}finally{await pg.close()}});
test('Basic app limit and cross-account project isolation are enforced in the database',async()=>{const pg=await fixture();try{const p=await create(pg);await assert.rejects(()=>create(pg),/App limit reached/);await assert.rejects(()=>pg.query(`select save_project($1,$2,1,'{}')`,[other,p.id]),/Not authorised/);await pg.query(`select save_project($1,$2,1,'{"a":"new"}')`,[user,p.id]);await assert.rejects(()=>pg.query(`select save_project($1,$2,1,'{}')`,[user,p.id]),/Version conflict/);}finally{await pg.close()}});
test('weekly credits expire without rollover, purchased credits remain',async()=>{const pg=await fixture();try{await pg.query(`update accounts set allowance_units=70,topup_units=150,credit_anchor=now()-interval '8 days',reset_at=now()-interval '1 day'where id=$1`,[user]);await pg.query('select ensure_account($1)',[user]);assert.equal((await a(pg)).allowance_units,100);assert.equal((await a(pg)).topup_units,150);await pg.query('select ensure_account($1)',[user]);assert.equal((await a(pg)).allowance_units,100);}finally{await pg.close()}});
test('reservations are idempotent, prevent overspending and settle once',async()=>{const pg=await fixture();try{const p=await create(pg),id=crypto.randomUUID();await pg.query(`select reserve_run($1,$2,$3,'gpt','Build',80)`,[user,id,p.id]);await pg.query(`select reserve_run($1,$2,$3,'gpt','Build',80)`,[user,id,p.id]);assert.equal((await a(pg)).allowance_units,20);await assert.rejects(()=>pg.query(`select reserve_run($1,$2,$3,'gpt','Build',30)`,[user,crypto.randomUUID(),p.id]),/Concurrent task limit reached/);await pg.query(`select finish_run($1,'completed',23,'done','{}','[]')`,[id]);assert.equal((await a(pg)).allowance_units,77);await pg.query(`select finish_run($1,'completed',23,'done','{}','[]')`,[id]);assert.equal((await a(pg)).allowance_units,77);await assert.rejects(()=>pg.query(`select reserve_run($1,$2,$3,'gpt','Build',78)`,[user,crypto.randomUUID(),p.id]),/Insufficient credits/);}finally{await pg.close()}});
test('expired reserved allowance cannot resurrect into the new week',async()=>{const pg=await fixture();try{const p=await create(pg),id=crypto.randomUUID();await pg.query(`select reserve_run($1,$2,$3,'gpt','Build',80)`,[user,id,p.id]);await pg.query(`update accounts set reset_at=now()-interval '1 day',credit_anchor=now()-interval '8 days'where id=$1`,[user]);await pg.query('select ensure_account($1)',[user]);await pg.query(`select finish_run($1,'failed',0,'failed','{}','[]')`,[id]);assert.equal((await a(pg)).allowance_units,100);}finally{await pg.close()}});
test('payment replay cannot grant duplicate top-ups and trial cannot be reused',async()=>{const pg=await fixture();try{await pg.query(`select apply_payment('cs_1',$1,'topup','basic',null,null,1000,null)`,[user]);await pg.query(`select apply_payment('cs_1',$1,'topup','basic',null,null,1000,null)`,[user]);assert.equal((await a(pg)).topup_units,1000);await pg.query(`select apply_payment('trial:sub1',$1,'trial','pro',now(),now()+interval '7 days',1000,'sub1')`,[user]);assert.equal((await a(pg)).allowance_units,1000);assert.equal((await a(pg)).trial_used,true);await assert.rejects(()=>pg.query(`select apply_payment('trial:sub2',$1,'trial','pro',now(),now()+interval '7 days',1000,'sub2')`,[user]),/Trial already used/);}finally{await pg.close()}});
test('older paid events do not shorten newer paid access',async()=>{const pg=await fixture();try{await pg.query(`select apply_payment('in_new',$1,'subscription','pro',now(),now()+interval '6 months',5500,'sub1')`,[user]);const date=(await a(pg)).paid_until;await pg.query(`select apply_payment('in_old',$1,'subscription','pro',now()-interval '2 months',now()-interval '1 month',5500,'sub1')`,[user]);assert.equal(String((await a(pg)).paid_until),String(date));}finally{await pg.close()}});
test('members require explicit acceptance and cannot grant themselves credits',async()=>{const pg=await fixture();try{await pg.query(`select add_member($1,'builder@example.com')`,[owner]);assert.equal((await a(pg)).workspace_id,null);await pg.query('select accept_workspace($1)',[user]);assert.equal((await a(pg)).workspace_id,owner);await assert.rejects(()=>pg.query(`select adjust_credits($1,$1,100,'self grant')`,[user]),/Not authorised/);}finally{await pg.close()}});
test('paid expiry archives surplus apps and restoration respects Basic limit',async()=>{const pg=await fixture();try{await pg.query(`select apply_payment('in_paid',$1,'subscription','pro',now()-interval '2 months',now()-interval '1 month',5500,'sub1')`,[user]);await pg.query(`update accounts set paid_until=now()+interval '1 month'where id=$1`,[user]);await create(pg);await create(pg);await pg.query(`update accounts set paid_until=now()-interval '1 minute'where id=$1`,[user]);await pg.query('select ensure_account($1)',[user]);const projects=(await pg.query<any>('select * from projects where owner_id=$1',[user])).rows;assert.equal(projects.filter(p=>!p.archived).length,1);const archived=projects.find(p=>p.archived);await assert.rejects(()=>pg.query('select archive_project($1,$2,false)',[user,archived.id]),/App limit reached/);await assert.rejects(()=>pg.query(`select save_project($1,$2,1,'{}')`,[user,archived.id]),/Not authorised/);}finally{await pg.close()}});
test('checkout leases prevent simultaneous subscription creation and require matching release token',async()=>{const pg=await fixture();try{const lease=crypto.randomUUID();await pg.query('select claim_checkout($1,$2)',[user,lease]);await assert.rejects(()=>pg.query('select claim_checkout($1,$2)',[user,crypto.randomUUID()]),/Checkout already in progress/);await pg.query('select release_checkout($1,$2)',[user,crypto.randomUUID()]);await assert.rejects(()=>pg.query('select claim_checkout($1,$2)',[user,crypto.randomUUID()]),/Checkout already in progress/);await pg.query('select release_checkout($1,$2)',[user,lease]);await pg.query('select claim_checkout($1,$2)',[user,crypto.randomUUID()]);}finally{await pg.close()}});
test('schedules cannot be created for free accounts or other peoples projects',async()=>{const pg=await fixture();try{const p=await create(pg);await assert.rejects(()=>pg.query(`select create_automation($1,$2,'Audit','gpt','Review',10,'weekly')`,[user,p.id]),/Not authorised/);await assert.rejects(()=>pg.query(`select create_automation($1,$2,'Audit','gpt','Review',10,'weekly')`,[owner,p.id]),/Not authorised/);}finally{await pg.close()}});
test('credit ledger reconciles across trial replacement, paid grant and an older invoice',async()=>{const pg=await fixture();try{await pg.query(`select apply_payment('trial:sub1',$1,'trial','pro',now(),now()+interval '7 days',1000,'sub1')`,[user]);await pg.query(`select apply_payment('in_current',$1,'subscription','pro',now()+interval '7 days',now()+interval '1 month 7 days',5500,'sub1')`,[user]);await pg.query(`select apply_payment('in_old',$1,'subscription','pro',now()-interval '2 months',now()-interval '1 month',5500,'sub1')`,[user]);const total=(await pg.query<any>('select sum(amount_units)::int as total from credit_ledger where owner_id=$1',[user])).rows[0].total;const acc=await a(pg);assert.equal(total,acc.allowance_units+acc.topup_units);}finally{await pg.close()}});
test('browser database roles cannot read private tables or call privileged functions',async()=>{const pg=await fixture();try{await pg.exec('set role authenticated');await assert.rejects(()=>pg.query('select * from accounts'),/permission denied/);await assert.rejects(()=>pg.query('select ensure_account($1)',[owner]),/permission denied/);await pg.exec('reset role');}finally{await pg.close()}});
