import {createClient} from '@supabase/supabase-js';
import {NextResponse} from 'next/server';
import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import type {Account} from './types';
export class ApiError extends Error {constructor(message:string,public status=400){super(message)}}
export function env(name:string){const value=process.env[name];if(!value)throw new ApiError(`Service setup required: ${name}`,503);return value;}
export function db(){return createClient(env('NEXT_PUBLIC_SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
export function check<T>(result:{data:T;error:unknown}){if(result.error){console.error('Database operation failed',result.error);throw new ApiError('The request could not be saved. Please try again.',500)}return result.data as NonNullable<T>;}
export async function rpc(name:string,args:Record<string,unknown>={}){const {data,error}=await db().rpc(name,args);if(error){const known=['Insufficient credits','App limit reached','Concurrent task limit reached','Version conflict','Not authorised','Trial already used','Member limit reached','Account unavailable','Checkout already in progress'];throw new ApiError(known.find(m=>error.message.includes(m))||'Database operation failed',known.some(m=>error.message.includes(m))?409:500)}return data;}
export async function identity(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token)throw new ApiError('Sign in to continue.',401);const {data,error}=await db().auth.getUser(token);if(error||!data.user)throw new ApiError('Please sign in again.',401);if(!data.user.email_confirmed_at)throw new ApiError('Verify your email to continue.',403);return data.user;}
export async function account(req:Request){const user=await identity(req);const a=await rpc('ensure_account',{p_user:user.id});return a as Account;}
export async function workspace(a:Account){if(!a.workspace_id)return a;const w=await rpc('ensure_account',{p_user:a.workspace_id}) as Account;if(w.tier!=='executive'){check(await db().from('accounts').update({workspace_id:null}).eq('id',a.id));a.workspace_id=null;return a;}return w;}
export async function owner(req:Request){const a=await account(req);if(a.role!=='owner')throw new ApiError('Owner access required.',403);return a;}
export async function project(a:Account,id:string){const w=await workspace(a);const p=check(await db().from('projects').select('*').eq('id',id).eq('owner_id',w.id).single());if(!p)throw new ApiError('Project not found.',404);return p;}
export function route(fn:(req:Request,context:any)=>Promise<unknown>){return async(req:Request,context:any)=>{try{if(req.method!=='GET'&&req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin&&req.headers.get('origin')!==process.env.NEXT_PUBLIC_APP_URL)throw new ApiError('Invalid request origin.',403);const result=await fn(req,context);return result instanceof Response?result:NextResponse.json(result,{headers:{'Cache-Control':'no-store'}})}catch(e){if(!(e instanceof ApiError))console.error(e);return NextResponse.json({error:e instanceof ApiError?e.message:'Request failed. Please try again.'},{status:e instanceof ApiError?e.status:500})}}}
export async function body(req:Request){const text=await req.text();if(text.length>650000)throw new ApiError('Request is too large.',413);try{return JSON.parse(text)}catch{throw new ApiError('Invalid request body.')}}
export function seal(text:string){const key=Buffer.from(env('INTEGRATION_ENCRYPTION_KEY'),'hex');if(key.length!==32)throw new ApiError('Integration encryption needs a 32-byte key.',503);const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([c.update(text,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),encrypted]).toString('base64');}
export function unseal(text:string){const b=Buffer.from(text,'base64'),d=createDecipheriv('aes-256-gcm',Buffer.from(env('INTEGRATION_ENCRYPTION_KEY'),'hex'),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString('utf8');}
export async function audit(actor:string,action:string,detail:Record<string,unknown>){check(await db().from('audit_log').insert({actor_id:actor,action,detail}));}
